
alias playjson='screpl com.typesafe.play%%play-json%2.2.2'
alias scalaz6='screpl org.scalaz%%scalaz-full%6.0.4'
alias json4s='screpl org.json4s%%json4s-native%3.2.7'
alias scalaz7='screpl org.scalaz%%scalaz-scalacheck-binding%7.1.0-M5'
alias scalaz70='screpl org.scalaz%%scalaz-core%7.0.5'
alias shapeless124='screpl com.chuusai%%shapeless%1.2.4'
alias shapeless-scalaz='screpl org.typelevel%%shapeless-scalaz%0.1.2'
alias spire='screpl org.spire-math%%spire%0.7.3'
alias nobox='screpl com.github.xuwei-k%%nobox%0.1.8'
alias applybuilder71='screpl com.github.xuwei-k%%applybuilder71%0.1.1'
alias applybuilder70='screpl com.github.xuwei-k%%applybuilder70%0.1.1'
alias ghscala-scalaj='screpl com.github.xuwei-k%%ghscala-scalaj%0.2.5'
alias ghscala-dispatch='screpl com.github.xuwei-k%%ghscala-dispatch%0.2.5'
alias ghscala-apache='screpl com.github.xuwei-k%%ghscala-apache%0.2.5'
alias iarray='screpl com.github.xuwei-k%%iarray%0.2.6'
alias play2scalaz='screpl com.github.xuwei-k%%play2scalaz%0.1.0'
alias scalaz=scalaz7

alias gg="git grep"
alias ls='ls -G'
alias ll='ls -l -o'
alias grep='grep -n -r'
alias tree='tree -C'
alias mkdir='mkdir -p'
alias cp='cp -r'
alias zip='zip -r'
alias less='less -R'
